### ISSUE TITLE
Add API documentation

### ISSUE THREAD

**Issue by Ty3r0X** [mumble-voip/mumble-plugin-cpp#6]
I couldn't find any API documentation for the mumble plugin API. I think it can be implemented with [Doxygen](https://www.doxygen.nl/index.html). If there is any resource I omitted, this issue can be ignored. Thanks!

**Comment by Krzmbrzl** [comment]
The API is documented in the corresponding C header files (e.g. https://github.com/mumble-voip/mumble-plugin-cpp/blob/master/include/mumble/plugin/internal/MumbleAPI_v_1_0_x.h) instead of in the C++ wrapper files. Together with the C++ function signature, I hope that things will make sense.

**Comment by Ty3r0X** [comment]
Yeah, it makes sense! Thanks!
